### ISSUE TITLE
Log level checking in interpolated string handlers is wrong 

### ISSUE THREAD

**Issue by ric15ni** [Tenacom/Louis#24]
### Affected version(s)

1.0.47-preview

### Is this a regression?

MAYBE - I don't know if any previous version had the same problem

### Context

When I call any method of LoggerExtensions that uses an interpolated string handler, it should check whether the desired logging level is enabled and skip evaluating the message entirely if not.

### Expected behavior

The correct logging level should be checked. For example, given this code:

```C#
using Louis.Logging;
using Microsoft.Extensions.Logging;

int Boom() => throw new Exception("Gotcha!");

void DemonstrateLoggingBug(ILogger logger) => logger.LogInformation($"Let's go {Boom()}!");
```

if the logger you pass to `DemonstrateLoggingBug` has only Critical logging enabled, `Boom` should not be called and no exception should be thrown.

### Actual behavior

The Critical logging level is checked instead of the actual logging level in use.

Given the example above, `DemonstrateLoggingBug` will throw an `Exception` with a message of `"Gotcha!"` _unless the **Critical** (instead of Information) logging level is disabled in the logger_.

### How to reproduce

See the code above.

### Configuration

All configurations are affected.

### Other information

I have tracked down the bug. It's quite simple actually, just some code that was probably copypasted and left as-is instead of changing the logging level to check:

- https://github.com/Tenacom/Louis/blob/72f701a05092667abab190aa1ec0ee74803ed834/src/Louis.Logging/LogInterpolatedStringHandler.Debug.cs#L32
- https://github.com/Tenacom/Louis/blob/72f701a05092667abab190aa1ec0ee74803ed834/src/Louis.Logging/LogInterpolatedStringHandler.Error.cs#L34
- https://github.com/Tenacom/Louis/blob/72f701a05092667abab190aa1ec0ee74803ed834/src/Louis.Logging/LogInterpolatedStringHandler.Information.cs#L32
- https://github.com/Tenacom/Louis/blob/72f701a05092667abab190aa1ec0ee74803ed834/src/Louis.Logging/LogInterpolatedStringHandler.Trace.cs#L32
- https://github.com/Tenacom/Louis/blob/72f701a05092667abab190aa1ec0ee74803ed834/src/Louis.Logging/LogInterpolatedStringHandler.Warning.cs#L32

**Comment by rdeago** [comment]
Thanks for reporting this bug @ric15ni!

Now guess who's in charge of fixing it? 😁

**Comment by ric15ni** [comment]
Looks like I pulled the shortest straw. 🤣 

On it!
