### ISSUE TITLE
ILogger wrapper that adds a prefix to all messages

### ISSUE THREAD

**Issue by ric15ni** [Tenacom/Louis#26]
### Reference version

1.0.59-preview

### Background and motivation

We need to prepend a constant string to all log entries generated by an object.

### Proposed enhancement

Create a wrapper class for `ILogger` (plus a similar one for `ILogger<T>`) that prepends a string, passed in the constructor, to every log entry.

### Implementation proposals

Create `PrefixedLogger` and `PrefixedLogger<T>` in `Louis.Logging`.

As a bonus, if the wrapped logger is of the same class, directly wrap its wrapped logger using a concatenation of the two prefixes. (Nice performance optimization at a very low cost.)

### Usage examples

```c#
public class Gizmo
{
    private readonly ILogger _logger;

    public Gizmo(ILogger logger)
    {
        Id = GenerateGizmoId(); // ...or whatever
        _logger = new PrefixedLogger(logger, $"[Gizmo:{Id}] ");
    }

    public string Id { get; }

    public void DoSomething()
    {
        _logger.LogInformation("Doing something...");
    }
}
```

...in the log (whose formatting I'm totally making up):

```text
2023-03-11 16:47:28 | Information | ClassNameOfGizmoOwner | [Gizmo:XYZ] Doing something...
```

### Risks

As with practically anything in a library, there's the risk of abuse. For example, someone could use prefixed loggers where scopes are more suitable. That's hardly the library's problem IMHO.

Of course performance would be impacted, but... when you need a prefix you need a prefix: either have a prefixed logger, or add the prefix to _all_ logging calls.

**Comment by rdeago** [comment]
All right @ric15ni - you are free... no, wait, you are _warmly invited_ to submit a PR for this. 😁
