### ISSUE TITLE
Add FluentExtensions.Invoke overloads with additional parameters

### ISSUE THREAD

**Issue by ric15ni** [Tenacom/Louis#51]
### Reference version

1.0.93-preview

### Background and motivation

The `Invoke` method found in `Louis.Fluency.FluentExtensions` can have an unexpected impact on performance when it is passed a lambda that uses any local variable or parameter of its containing method, or any instance member of its containing type.

This is due to the creation of a [closure](https://csharpindepth.com/Articles/Closures) to hold the lambda together with the data it needs.

Consider the following code:

```c#
interface IMotor
{
    void SetSpeed(int speed);
    void TurnOn();
    void TurnOff();
}

class MotorizedGadget
{
    private readonly IMotor _motor;

    // ...

    public static MotorizedGadget CreateRunning(int speed)
        => new()
            .Invoke(x => x.SetSpeed(speed))
            .Invoke(x => x.TurnOn());
}
```

Every call to `MotorizedGadget.CreateRunning` will create and then destroy a closure object. The garbage collector will have to reclaim the memory used by the closure object at some later time.

When a method containing a closure is called a sufficient number of times in a short span of time, the performance impact [is all but negligible](https://medium.com/criteo-engineering/beware-lambda-captures-383efe3a4345).

### Proposed enhancement

Since closures are created automatically by the compiler, there's no avoiding them... except by copying the data _into the lambda itself_.

Suppose there were an overload of `Invoke` that allowed for an additional parameter for the lambda:

```c#
public static T Invoke<T, TArg>(this T @this, TArg arg, Action<T, TArg> action);
```

If we rewrite `MotorizedGadget.CreateRunning` like this:

```c#
public static MotorizedGadget CreateRunning(int speed)
    => new()
        .Invoke(speed, (x, s) => x.SetSpeed(s))
        .Invoke(x => x.TurnOn());
```

no closure needs to be created, as `speed` is passed as an argument to the first lambda, which therefore has no need to access any data external to it.

### Implementation proposals

Implementation is pretty straightforward:

```c#
using System;
using CommunityToolkit.Diagnostics;

namespace Louis.Fluency;

partial class FluentExtensions
{
    public static T Invoke<T, TArg>(this T @this, TArg arg, Action<T, TArg> action)
    {
        Guard.IsNotNull(@this);
        Guard.IsNotNull(action);

        action(@this, arg);
        return @this;
    }

    public static T Invoke<T, TArg1, TArg2>(this T @this, TArg1 arg1, TArg2 arg2, Action<T, TArg1, TArg2> action)
    {
        Guard.IsNotNull(@this);
        Guard.IsNotNull(action);

        action(@this, arg1, arg2);
        return @this;
    }

    // ...and so on, if we want even more parameters.
}
```

I'd pass additional arguments before the lambda to preserve code readability even with long lambdas, potentially spanning multiple lines.

### Usage examples

See the code in the "Proposed enhancement" section.

### Risks

I cannot see any risk stemming from the implementation of the proposed methods in `FluentExtensions`.

**Comment by rdeago** [comment]
This looks good.

In some of our internal-use libraries (mostly bound to be open-sourced btw) there are extension methods that do exactly that, but for a restricted number of specific types. The proposed `Invoke` overloads would overlap with those methods, making them redundant and thus simplifying library code.

@ric15ni I'm assigning you this issue. Please make it support 1 to 4 additional parameters (so to make existing specialized methods completely redundant) but no more than that, at least for now.
