### ISSUE TITLE
Asynchronous background services

### ISSUE THREAD

**Issue by rdeago** [Tenacom/Louis#56]
### Reference version

1.0.101-preview

### Background and motivation

The `AsyncWorker` class, present in the first preview versions of L.o.U.I.S. and retired in 1.0.0-preview.7 to avoid feature creep, should be included after all.

The alternative to `AsyncWorker` would be [`BackgroundService`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice), but it comes with some shortcomings, such as:

- an additional package dependency on `Microsoft.Extensions.Hosting`;
- when service cancellation is requested, `OperationCanceledException`s are not caught, resulting in 
- no way to know the state of a service (not started, starting, running, stopping);
- no way to stop a service and wait for its completion.

These are all features `AsyncWorker` provided.

On the other hand, `BackgroundService` features seamless integration with ASP.NET Core and `Microsoft.Extensions.Hosting`, because it implements [`IHostedService`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice). Said integration is a desirable feature for `AsyncWorker` too; however, it should be implemented in a separate assembly, without making `Louis` depend on `Microsoft.Extensions.Hosting`.

### Proposed enhancement

Bring back `Louis.Threading.AsyncWorker`, adding _optional_ integration with Microsoft platform extensions.

### Async workers

- Bring back `Louis.Threading.AsyncWorker`, renaming it to `AsyncService` to underline its similarity in purpose to `BackgroundService`.
- Extract basic functionality into a DI-friendly `IAsyncService` interface.
- Add virtual methods that can be overridden to log lifetime-related events (start, stop, cancellation, etc.)

### Integration with Microsoft extensions

- Create a `Louis.Extensions.Hosting` library, depending on `Microsoft.Extensions.Hosting.Abstractions`, `Microsoft.Extensions.Logging.Abstractions`, `Microsoft.Extensions.DependencyInjection.Abstractions`.
- Subclass `AsyncService` into an `AsyncHostedService` class that uses an [`ILogger`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger) to log lifetime-related events.
- Integration of `AsyncService` with `Microsoft.Extensions.Hosting` may be achieved in different ways:
  * either implementing `IHostedService` in `AsyncHostedService`, if possible;
  * or creating the following:
    - a hosted service that starts and stops all `IAsyncService`-derived services obtained from DI;
    - an extension method `IHostBuilder.AddAsyncServiceSupport` that adds said hosted service to the hst builder's service collection;
    - an extension method `IServiceCollection.AddAsyncService` with similar functionality to [`AddHostedService`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionhostedserviceextensions.addhostedservice).

### Usage examples

(to be added)

### Risks

If starting and stopping async services via a hosted service, we should start / stop as many as possible, but not more than a certain number, in parallel, lest we incur a performance penalty.

**Comment by ric15ni** [comment]
I may have a PR ready in a day.
